# Generated by Django 5.0.14 on 2025-07-21 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultantProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('mobile', models.CharField(blank=True, max_length=15, null=True)),
                ('bank_account_name', models.CharField(max_length=255)),
                ('bank_account_number', models.CharField(max_length=50)),
                ('bank_ifsc', models.CharField(max_length=20)),
                ('bank_branch_name', models.CharField(max_length=255)),
                ('bank_name', models.CharField(max_length=255)),
                ('cost_type', models.CharField(choices=[('hourly', 'Cost per Hour'), ('monthly', 'Monthly Cost')], default='hourly', max_length=10)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('weekly_commitment', models.DecimalField(blank=True, decimal_places=2, help_text='Hours per week willing to consult', max_digits=5, null=True)),
                ('availability', models.JSONField(blank=True, help_text='Availability as JSON: days and time ranges', null=True)),
                ('agreement_document', models.FileField(blank=True, null=True, upload_to='agreements/')),
                ('details', models.TextField(blank=True, null=True)),
                ('total_experience', models.DecimalField(blank=True, decimal_places=2, help_text='Total years of professional experience', max_digits=4, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ConsultantSkillExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience_years', models.DecimalField(blank=True, decimal_places=2, help_text='Years of experience in this skill', max_digits=4, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('month', models.DateField()),
                ('file', models.FileField(upload_to='invoices/')),
                ('status', models.CharField(choices=[('awaiting_review', 'Awaiting Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('paid', 'Paid'), ('partially_paid', 'Partially Paid'), ('sent_to_banking', 'Sent to Banking'), ('sent_to_consultant', 'Sent to Consultant')], default='awaiting_review', max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Timesheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField()),
                ('file', models.FileField(upload_to='timesheets/')),
                ('status', models.CharField(choices=[('approved', 'Approved'), ('pending', 'Pending'), ('rejected', 'Rejected'), ('awaiting_review', 'Awaiting Review')], default='awaiting_review', max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
