# Generated by Django 5.0.14 on 2025-07-14 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='consultantBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('consultant_field', models.CharField(choices=[('Business Strategy', 'Business Strategy'), ('Financial Planning', 'Financial Planning'), ('Legal Advice', 'Legal Advice'), ('Career Counseling', 'Career Counseling'), ('Health & Wellness', 'Health & Wellness'), ('Technology', 'Technology'), ('Other', 'Other')], max_length=50)),
                ('other_consultant_field', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ConsultantProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('mobile', models.CharField(blank=True, max_length=15, null=True)),
                ('bank_account_name', models.CharField(max_length=255)),
                ('bank_account_number', models.CharField(max_length=50)),
                ('bank_ifsc', models.CharField(max_length=20)),
                ('bank_branch_name', models.CharField(max_length=255)),
                ('bank_name', models.CharField(max_length=255)),
                ('cost_per_hour', models.DecimalField(decimal_places=2, max_digits=10)),
                ('agreement_document', models.FileField(blank=True, null=True, upload_to='agreements/')),
                ('details', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('month', models.DateField()),
                ('file', models.FileField(upload_to='invoices/')),
                ('status', models.CharField(choices=[('awaiting_review', 'Awaiting Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('paid', 'Paid'), ('partially_paid', 'Partially Paid'), ('sent_to_banking', 'Sent to Banking'), ('sent_to_consultant', 'Sent to Consultant')], default='awaiting_review', max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Timesheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField()),
                ('file', models.FileField(upload_to='timesheets/')),
                ('status', models.CharField(choices=[('approved', 'Approved'), ('pending', 'Pending'), ('rejected', 'Rejected'), ('awaiting_review', 'Awaiting Review')], default='awaiting_review', max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
