# Generated by Django 5.0.14 on 2025-07-21 15:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('consultant', '0001_initial'),
        ('custom_admin', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='consultantprofile',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultant_profiles', to='custom_admin.consultantstatus'),
        ),
        migrations.AddField(
            model_name='consultantprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='consultant_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='consultantskillexperience',
            name='consultant_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_experiences', to='consultant.consultantprofile'),
        ),
        migrations.AddField(
            model_name='consultantskillexperience',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='custom_admin.skill'),
        ),
        migrations.AddField(
            model_name='consultantprofile',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='consultant_profiles', through='consultant.ConsultantSkillExperience', to='custom_admin.skill'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='consultant',
            field=models.ForeignKey(limit_choices_to={'role': 'consultant'}, on_delete=django.db.models.deletion.CASCADE, related_name='consultant_invoices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='timesheet',
            name='consultant',
            field=models.ForeignKey(limit_choices_to={'role': 'consultant'}, on_delete=django.db.models.deletion.CASCADE, related_name='consultant_timesheets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='consultantskillexperience',
            unique_together={('consultant_profile', 'skill')},
        ),
        migrations.AlterUniqueTogether(
            name='timesheet',
            unique_together={('consultant', 'month')},
        ),
    ]
