# Generated by Django 5.0.14 on 2025-07-23 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultant', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultantprofile',
            name='linkedin_profile',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
