# Generated by Django 5.0.14 on 2025-07-28 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultant', '0003_consultantprofile_linkedin_profile'),
    ]

    operations = [
        migrations.RunSQL(
            "ALTER TABLE consultant_consultantprofile DROP CONSTRAINT IF EXISTS consultant_consultantprofile_availability_c8cbe799_check",
            "-- No reverse operation needed"
        ),
    ]
