# Generated by Django 5.0.14 on 2025-07-16 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='consultantBooking',
            new_name='ProspectiveConsultant',
        ),
    ]
