# Generated by Django 5.0.14 on 2025-07-16 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0002_rename_consultantbooking_prospectiveconsultant'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospectiveconsultant',
            name='linkedin',
            field=models.URLField(blank=True, help_text='LinkedIn profile URL', null=True),
        ),
    ]
