# Generated by Django 5.0.14 on 2025-06-03 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0002_skill_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultantprofile',
            name='agreement_document',
            field=models.FileField(blank=True, null=True, upload_to='agreements/'),
        ),
        migrations.AddField(
            model_name='consultantprofile',
            name='details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
