# Generated by Django 5.0.14 on 2025-06-04 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0003_consultantprofile_agreement_document_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultantprofile',
            name='mobile',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='consultantprofile',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
