# Generated by Django 5.0.14 on 2025-06-04 09:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0004_consultantprofile_mobile_consultantprofile_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultantStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected'), ('to_be_reviewed', 'To Be Reviewed')], default='to_be_reviewed', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='consultant_status', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='ConsultantProfile',
        ),
    ]
