# Generated by Django 5.0.14 on 2025-06-04 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0005_consultantstatus_delete_consultantprofile'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='skill',
            table='custom_admin_skill_master',
        ),
    ]
