# Generated by Django 5.0.14 on 2025-06-04 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0004_alter_consultantprofile_user'),
        ('custom_admin', '0006_alter_skill_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='consultation_invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_admin_invoices', to='consultation.invoice'),
        ),
        migrations.AddField(
            model_name='timesheet',
            name='consultation_timesheet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_admin_timesheets', to='consultation.timesheet'),
        ),
        migrations.AddField(
            model_name='timesheet',
            name='status',
            field=models.CharField(choices=[('approved', 'Approved'), ('pending', 'Pending'), ('rejected', 'Rejected'), ('awaiting_review', 'Awaiting Review')], default='awaiting_review', max_length=20),
        ),
    ]
