# Generated by Django 5.0.14 on 2025-06-04 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0001_initial'),
        ('custom_admin', '0005_consultantstatus_delete_consultantprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultantprofile',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultation_profiles', to='custom_admin.consultantstatus'),
        ),
    ]
