# Generated by Django 5.0.14 on 2025-06-04 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0002_alter_consultantprofile_status'),
        ('custom_admin', '0006_alter_skill_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultantprofile',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='consultant_profiles', to='custom_admin.skill'),
        ),
    ]
