# Generated by Django 5.0.14 on 2025-06-05 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0005_timesheetentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='timesheetentry',
            name='task_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
