# Generated by Django 5.0.14 on 2025-06-16 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0006_timesheetentry_task_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('awaiting_review', 'Awaiting Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('paid', 'Paid'), ('partially_paid', 'Partially Paid'), ('sent_to_banking', 'Sent to Banking'), ('sent_to_consultant', 'Sent to Consultant')], default='awaiting_review', max_length=20),
        ),
    ]
