# Generated by Django 5.0.14 on 2025-06-17 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0007_alter_invoice_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='timesheetentry',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='timesheetentry',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
