# Generated by Django 5.0.14 on 2025-06-17 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0008_timesheetentry_end_time_timesheetentry_start_time'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TimesheetEntry',
        ),
    ]
